import {Materials} from "./materials";

export enum EGenerator {
    SmallGasTurbine = "Small gas turbine",
    DieselGenerator = "Diesel generator",
    SemifluidGenerator = "Semifluid generator",
}

export const MaterialPower = {
    [Materials.HYDROGEN.id]: {generator: EGenerator.SmallGasTurbine, power: 20000},
    ["NATURAL_GAS_CELL"]: {generator: EGenerator.SmallGasTurbine, power: 20000},
    [Materials.WOOD_GAS.id]: {generator: EGenerator.SmallGasTurbine, power: 24000},
    [Materials.CARBON_MONOXIDE.id]: {generator: EGenerator.SmallGasTurbine, power: 24000},
    [Materials.SULFURIC_GAS.id]: {generator: EGenerator.SmallGasTurbine, power: 25000},
    [Materials.SULFURIC_NAPHTA.id]: {generator: EGenerator.SmallGasTurbine, power: 40000},
    ["IC2BIOGAS"]: {generator: EGenerator.SmallGasTurbine, power: 20000},
    ["BIOGAS"]: {generator: EGenerator.SmallGasTurbine, power: 20000},
    [Materials.COAL_GAS.id]: {generator: EGenerator.SmallGasTurbine, power: 96000},
    [Materials.METHANE_GAS.id]: {generator: EGenerator.SmallGasTurbine, power: 104000},
    [Materials.ETHYLENE.id]: {generator: EGenerator.SmallGasTurbine, power: 128000},
    [Materials.REFINERY_GAS.id]: {generator: EGenerator.SmallGasTurbine, power: 160000},
    [Materials.ETHANE.id]: {generator: EGenerator.SmallGasTurbine, power: 168000},
    [Materials.PROPENE.id]: {generator: EGenerator.SmallGasTurbine, power: 192000},
    [Materials.BUTADIENE.id]: {generator: EGenerator.SmallGasTurbine, power: 206000},
    [Materials.PROPANE.id]: {generator: EGenerator.SmallGasTurbine, power: 232000},
    ["ROCKET_FUEL"]: {generator: EGenerator.SmallGasTurbine, power: 250000},
    [Materials.BUTENE.id]: {generator: EGenerator.SmallGasTurbine, power: 256000},
    [Materials.PHENOL.id]: {generator: EGenerator.SmallGasTurbine, power: 288000},
    [Materials.BENZENE.id]: {generator: EGenerator.SmallGasTurbine, power: 288000},
    [Materials.BUTANE.id]: {generator: EGenerator.SmallGasTurbine, power: 296000},
    ["LPG"]: {generator: EGenerator.SmallGasTurbine, power: 320000},
    [Materials.NAPHTA.id]: {generator: EGenerator.SmallGasTurbine, power: 320000},
    [Materials.TOLUENE.id]: {generator: EGenerator.SmallGasTurbine, power: 328000},

    ["SHORT_MEAD"]: {generator: EGenerator.DieselGenerator, power: 4000},
    ["biofuel"]: {generator: EGenerator.DieselGenerator, power: 6000},
    ["biomass"]: {generator: EGenerator.DieselGenerator, power: 8000},
    [Materials.CREOSOTE_OIL.id]: {generator: EGenerator.DieselGenerator, power: 8000},
    [Materials.BC_OIL.id]: {generator: EGenerator.DieselGenerator, power: 16000},
    [Materials.SULFURIC_LIGHT_FUEL.id]: {generator: EGenerator.DieselGenerator, power: 40000},
    [Materials.OCTANE.id]: {generator: EGenerator.DieselGenerator, power: 80000},
    [Materials.METHANOL.id]: {generator: EGenerator.DieselGenerator, power: 84000},
    [Materials.ETHANOL.id]: {generator: EGenerator.DieselGenerator, power: 192000},
    ["BIODIESEL"]: {generator: EGenerator.DieselGenerator, power: 192000},
    ["DIESEL"]: {generator: EGenerator.DieselGenerator, power: 480000},
    ["GASOLINE"]: {generator: EGenerator.DieselGenerator, power: 576000},
    ["CETANE_BOOSTED_DIESEL"]: {generator: EGenerator.DieselGenerator, power: 720000},
    ["BUTANOL"]: {generator: EGenerator.DieselGenerator, power: 1125000},
    ["HIGH_OCTANE_GASOLINE"]: {generator: EGenerator.DieselGenerator, power: 1728000},

    ["SEED_OIL"]: {generator: EGenerator.SemifluidGenerator, power: 4000},
    ["FISH_OIL"]: {generator: EGenerator.SemifluidGenerator, power: 4000},
    ["RAW_ANIMAL_WASTE"]: {generator: EGenerator.SemifluidGenerator, power: 12000},
    [Materials.COAL_TAR.id]: {generator: EGenerator.SemifluidGenerator, power: 16000},
    ["BIOMASS"]: {generator: EGenerator.SemifluidGenerator, power: 16000},
    ["MANURE_SLURRY"]: {generator: EGenerator.SemifluidGenerator, power: 24000},
    ["FERTILE_MANURE_SLURRY"]: {generator: EGenerator.SemifluidGenerator, power: 32000},
    ["COAL_TAR_OIL"]: {generator: EGenerator.SemifluidGenerator, power: 32000},
    [Materials.LIGHT_OIL.id]: {generator: EGenerator.SemifluidGenerator, power: 40000},
    [Materials.BC_OIL.id]: {generator: EGenerator.SemifluidGenerator, power: 40000},
    [Materials.CREOSOTE_OIL.id]: {generator: EGenerator.SemifluidGenerator, power: 48000},
    ["RAW_OIL"]: {generator: EGenerator.SemifluidGenerator, power: 60000},
    [Materials.HEAVY_OIL.id]: {generator: EGenerator.SemifluidGenerator, power: 60000},
    ["SULFURIC_COAL_TAR_OIL"]: {generator: EGenerator.SemifluidGenerator, power: 64000},
    [Materials.SULFURIC_HEAVY_FUEL.id]: {generator: EGenerator.SemifluidGenerator, power: 80000},
    [Materials.HEAVY_FUEL.id]: {generator: EGenerator.SemifluidGenerator, power: 360000},
};
