import {Materials} from "./materials";
import {Machine} from "../Machine";
import {Recipe} from "../Recipe";
import {MaterialVolume} from "../MaterialVolume";

export const Recipes = [
    // oil distillating
    new Recipe([new MaterialVolume(Materials.BC_OIL, 25)], [new MaterialVolume(Materials.SULFURIC_GAS, 30)], 24, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.BC_OIL, 25)], [new MaterialVolume(Materials.SULFURIC_LIGHT_FUEL, 25)], 24, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.BC_OIL, 25)], [new MaterialVolume(Materials.SULFURIC_NAPHTA, 10)], 24, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.BC_OIL, 50)], [new MaterialVolume(Materials.SULFURIC_HEAVY_FUEL, 15)], 24, Machine.Distillery),

    new Recipe([new MaterialVolume(Materials.HEAVY_OIL, 50)], [new MaterialVolume(Materials.SULFURIC_GAS, 30)], 24, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_OIL, 50)], [new MaterialVolume(Materials.SULFURIC_HEAVY_FUEL, 125)], 24, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_OIL, 100)], [new MaterialVolume(Materials.SULFURIC_LIGHT_FUEL, 45)], 24, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_OIL, 100)], [new MaterialVolume(Materials.SULFURIC_NAPHTA, 15)], 24, Machine.Distillery),

    new Recipe([new MaterialVolume(Materials.LIGHT_OIL, 75)], [new MaterialVolume(Materials.SULFURIC_HEAVY_FUEL, 5)], 24, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_OIL, 75)], [new MaterialVolume(Materials.SULFURIC_LIGHT_FUEL, 10)], 24, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_OIL, 75)], [new MaterialVolume(Materials.SULFURIC_GAS, 120)], 24, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_OIL, 75)], [new MaterialVolume(Materials.SULFURIC_NAPHTA, 15)], 24, Machine.Distillery),

    new Recipe([new MaterialVolume(Materials.SULFURIC_GAS, 16000), new MaterialVolume(Materials.HYDROGEN, 2000)], [new MaterialVolume(Materials.REFINERY_GAS, 16000), new MaterialVolume(Materials.HYDROGEN_SULFIDE, 1000)], 30, Machine.ChemicalReactor),
    new Recipe([new MaterialVolume(Materials.SULFURIC_NAPHTA, 12000), new MaterialVolume(Materials.HYDROGEN, 2000)], [new MaterialVolume(Materials.NAPHTA, 12000), new MaterialVolume(Materials.HYDROGEN_SULFIDE, 1000)], 30, Machine.ChemicalReactor),
    new Recipe([new MaterialVolume(Materials.SULFURIC_LIGHT_FUEL, 12000), new MaterialVolume(Materials.HYDROGEN, 2000)], [new MaterialVolume(Materials.LIGHT_FUEL, 12000), new MaterialVolume(Materials.HYDROGEN_SULFIDE, 1000)], 30, Machine.ChemicalReactor),
    new Recipe([new MaterialVolume(Materials.SULFURIC_HEAVY_FUEL, 8000), new MaterialVolume(Materials.HYDROGEN, 2000)], [new MaterialVolume(Materials.HEAVY_FUEL, 8000), new MaterialVolume(Materials.HYDROGEN_SULFIDE, 1000)], 30, Machine.ChemicalReactor),

    // refinery gas distillating
    new Recipe([new MaterialVolume(Materials.REFINERY_GAS, 40)], [new MaterialVolume(Materials.METHANE_GAS, 30)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.REFINERY_GAS, 40)], [new MaterialVolume(Materials.ETHANE, 4)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.REFINERY_GAS, 50)], [new MaterialVolume(Materials.HELIUM_GAS, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.REFINERY_GAS, 50)], [new MaterialVolume(Materials.BUTANE, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.REFINERY_GAS, 100)], [new MaterialVolume(Materials.PROPANE, 7)], 30, Machine.Distillery),

    // heavy fuel distillating
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL, 10)], [new MaterialVolume(Materials.TOLUENE, 4)], 24, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL, 10)], [new MaterialVolume(Materials.BENZENE, 4)], 24, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL, 20)], [new MaterialVolume(Materials.PHENOL, 5)], 24, Machine.Distillery),

    // naphta cracking
    new Recipe([new MaterialVolume(Materials.NAPHTA, 250), new MaterialVolume(Materials.HYDROGEN, 1000)], [new MaterialVolume(Materials.NAPHTA_H_MOD, 200)], 30, Machine.CrackingInChemicalReactor),
    new Recipe([new MaterialVolume(Materials.NAPHTA, 500), new MaterialVolume(Materials.HYDROGEN, 1000)], [new MaterialVolume(Materials.NAPHTA_H_LIG, 400)], 30, Machine.CrackingInChemicalReactor),
    new Recipe([new MaterialVolume(Materials.NAPHTA, 500), new MaterialVolume(Materials.HYDROGEN, 3000)], [new MaterialVolume(Materials.NAPHTA_H_SEV, 400)], 30, Machine.CrackingInChemicalReactor),
    new Recipe([new MaterialVolume(Materials.NAPHTA, 1000), new MaterialVolume(Materials.STEAM, 1000)], [new MaterialVolume(Materials.NAPHTA_S_LIG, 800)], 30, Machine.CrackingInChemicalReactor),
    new Recipe([new MaterialVolume(Materials.NAPHTA, 1000), new MaterialVolume(Materials.STEAM, 1000)], [new MaterialVolume(Materials.NAPHTA_S_MOD, 800)], 30, Machine.CrackingInChemicalReactor),
    new Recipe([new MaterialVolume(Materials.NAPHTA, 1000), new MaterialVolume(Materials.STEAM, 1000)], [new MaterialVolume(Materials.NAPHTA_S_SEV, 800)], 30, Machine.CrackingInChemicalReactor),
    // light fuel cracking
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL, 250), new MaterialVolume(Materials.HYDROGEN, 1000)], [new MaterialVolume(Materials.LIGHT_FUEL_H_MOD, 200)], 30, Machine.CrackingInChemicalReactor),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL, 500), new MaterialVolume(Materials.HYDROGEN, 1000)], [new MaterialVolume(Materials.LIGHT_FUEL_H_LIG, 400)], 30, Machine.CrackingInChemicalReactor),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL, 500), new MaterialVolume(Materials.HYDROGEN, 3000)], [new MaterialVolume(Materials.LIGHT_FUEL_H_SEV, 400)], 30, Machine.CrackingInChemicalReactor),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL, 1000), new MaterialVolume(Materials.STEAM, 1000)], [new MaterialVolume(Materials.LIGHT_FUEL_S_LIG, 800)], 30, Machine.CrackingInChemicalReactor),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL, 1000), new MaterialVolume(Materials.STEAM, 1000)], [new MaterialVolume(Materials.LIGHT_FUEL_S_MOD, 800)], 30, Machine.CrackingInChemicalReactor),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL, 1000), new MaterialVolume(Materials.STEAM, 1000)], [new MaterialVolume(Materials.LIGHT_FUEL_S_SEV, 800)], 30, Machine.CrackingInChemicalReactor),
    // heavy fuel cracking
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL, 250), new MaterialVolume(Materials.HYDROGEN, 1000)], [new MaterialVolume(Materials.HEAVY_FUEL_H_MOD, 200)], 30, Machine.CrackingInChemicalReactor),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL, 500), new MaterialVolume(Materials.HYDROGEN, 1000)], [new MaterialVolume(Materials.HEAVY_FUEL_H_LIG, 400)], 30, Machine.CrackingInChemicalReactor),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL, 500), new MaterialVolume(Materials.HYDROGEN, 3000)], [new MaterialVolume(Materials.HEAVY_FUEL_H_SEV, 400)], 30, Machine.CrackingInChemicalReactor),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL, 1000), new MaterialVolume(Materials.STEAM, 1000)], [new MaterialVolume(Materials.HEAVY_FUEL_S_LIG, 800)], 30, Machine.CrackingInChemicalReactor),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL, 1000), new MaterialVolume(Materials.STEAM, 1000)], [new MaterialVolume(Materials.HEAVY_FUEL_S_MOD, 800)], 30, Machine.CrackingInChemicalReactor),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL, 1000), new MaterialVolume(Materials.STEAM, 1000)], [new MaterialVolume(Materials.HEAVY_FUEL_S_SEV, 800)], 30, Machine.CrackingInChemicalReactor),

    // cracked heavy fuel distillating - h mod
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_H_MOD, 100)], [new MaterialVolume(Materials.ETHANE, 10)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_H_MOD, 100)], [new MaterialVolume(Materials.METHANE_GAS, 10)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_H_MOD, 100)], [new MaterialVolume(Materials.LIGHT_FUEL, 40)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_H_MOD, 100)], [new MaterialVolume(Materials.NAPHTA, 40)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_H_MOD, 100)], [new MaterialVolume(Materials.PROPANE, 15)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_H_MOD, 100)], [new MaterialVolume(Materials.BUTANE, 15)], 30, Machine.Distillery),
    // cracked heavy fuel distillating - h lig
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_H_LIG, 100)], [new MaterialVolume(Materials.PROPANE, 10)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_H_LIG, 100)], [new MaterialVolume(Materials.NAPHTA, 10)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_H_LIG, 100)], [new MaterialVolume(Materials.LIGHT_FUEL, 60)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_H_LIG, 100)], [new MaterialVolume(Materials.BUTANE, 10)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_H_LIG, 200)], [new MaterialVolume(Materials.ETHANE, 15)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_H_LIG, 200)], [new MaterialVolume(Materials.METHANE_GAS, 15)], 30, Machine.Distillery),
    // cracked heavy fuel distillating - h sev
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_H_SEV, 100)], [new MaterialVolume(Materials.NAPHTA, 25)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_H_SEV, 100)], [new MaterialVolume(Materials.BUTANE, 30)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_H_SEV, 100)], [new MaterialVolume(Materials.PROPANE, 30)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_H_SEV, 100)], [new MaterialVolume(Materials.LIGHT_FUEL, 20)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_H_SEV, 200)], [new MaterialVolume(Materials.METHANE_GAS, 35)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_H_SEV, 200)], [new MaterialVolume(Materials.ETHANE, 35)], 30, Machine.Distillery),
    // cracked heavy fuel distillating - s lig
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.LIGHT_FUEL, 300), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.BUTADIENE, 15), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.ETHANE, 5), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.BUTENE, 25), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.PROPENE, 30), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.BENZENE, 125), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.PROPANE, 3), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.TOLUENE, 25), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.METHANE_GAS, 50), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.ETHYLENE, 50), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.NAPHTA, 50), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    // cracked heavy fuel distillating - s mod
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_MOD, 500)], [new MaterialVolume(Materials.BUTENE, 20), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_MOD, 500)], [new MaterialVolume(Materials.TOLUENE, 20), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_MOD, 500)], [new MaterialVolume(Materials.BENZENE, 100), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_MOD, 500)], [new MaterialVolume(Materials.LIGHT_FUEL, 100), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_MOD, 500)], [new MaterialVolume(Materials.NAPHTA, 100), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_MOD, 500)], [new MaterialVolume(Materials.PROPENE, 25), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_MOD, 1000)], [new MaterialVolume(Materials.ETHYLENE, 75), new MaterialVolume(Materials.CARBON_T_P, 2)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_MOD, 1000)], [new MaterialVolume(Materials.METHANE_GAS, 75), new MaterialVolume(Materials.CARBON_T_P, 2)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_MOD, 1000)], [new MaterialVolume(Materials.ETHANE, 7), new MaterialVolume(Materials.CARBON_T_P, 2)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_MOD, 1000)], [new MaterialVolume(Materials.PROPANE, 5), new MaterialVolume(Materials.CARBON_T_P, 2)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_MOD, 1000)], [new MaterialVolume(Materials.BUTADIENE, 25), new MaterialVolume(Materials.CARBON_T_P, 2)], 30, Machine.Distillery),
    // cracked heavy fuel distillating - s sev
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.ETHYLENE, 150), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.BENZENE, 400), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.BUTENE, 80), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.NAPHTA, 125), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.BUTADIENE, 50), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.PROPENE, 100), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.LIGHT_FUEL, 100), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.METHANE_GAS, 150), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.PROPANE, 10), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.ETHANE, 15), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.HEAVY_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.TOLUENE, 80), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),

    // cracked light fuel distillating - h mod
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_H_MOD, 100)], [new MaterialVolume(Materials.BUTANE, 20)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_H_MOD, 100)], [new MaterialVolume(Materials.OCTANE, 5)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_H_MOD, 100)], [new MaterialVolume(Materials.PROPANE, 110)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_H_MOD, 100)], [new MaterialVolume(Materials.NAPHTA, 50)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_H_MOD, 100)], [new MaterialVolume(Materials.METHANE_GAS, 40)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_H_MOD, 100)], [new MaterialVolume(Materials.ETHANE, 40)], 30, Machine.Distillery),
    // cracked light fuel distillating - h lig
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_H_LIG, 100)], [new MaterialVolume(Materials.OCTANE, 10)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_H_LIG, 100)], [new MaterialVolume(Materials.NAPHTA, 80)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_H_LIG, 100)], [new MaterialVolume(Materials.PROPANE, 20)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_H_LIG, 100)], [new MaterialVolume(Materials.BUTANE, 15)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_H_LIG, 200)], [new MaterialVolume(Materials.METHANE_GAS, 25)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_H_LIG, 200)], [new MaterialVolume(Materials.ETHANE, 25)], 30, Machine.Distillery),
    // cracked light fuel distillating - h sev
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_H_SEV, 100)], [new MaterialVolume(Materials.NAPHTA, 20)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_H_SEV, 100)], [new MaterialVolume(Materials.OCTANE, 2)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_H_SEV, 100)], [new MaterialVolume(Materials.ETHANE, 150)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_H_SEV, 100)], [new MaterialVolume(Materials.METHANE_GAS, 150)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_H_SEV, 200)], [new MaterialVolume(Materials.BUTANE, 25)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_H_SEV, 200)], [new MaterialVolume(Materials.PROPANE, 25)], 30, Machine.Distillery),
    // cracked light fuel distillating - s lig
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.TOLUENE, 40), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.ETHYLENE, 50), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.METHANE_GAS, 50), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.ETHANE, 10), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.PROPANE, 20), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.BUTENE, 75), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.PROPENE, 150), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.BUTADIENE, 60), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.BENZENE, 200), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.NAPHTA, 400), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_LIG, 1000)], [new MaterialVolume(Materials.HEAVY_FUEL, 150), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    // cracked light fuel distillating - s mod
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_MOD, 500)], [new MaterialVolume(Materials.HEAVY_FUEL, 50), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_MOD, 500)], [new MaterialVolume(Materials.BUTENE, 45), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_MOD, 500)], [new MaterialVolume(Materials.METHANE_GAS, 75), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_MOD, 500)], [new MaterialVolume(Materials.ETHANE, 15), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_MOD, 500)], [new MaterialVolume(Materials.TOLUENE, 25), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_MOD, 500)], [new MaterialVolume(Materials.PROPENE, 100), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_MOD, 1000)], [new MaterialVolume(Materials.ETHYLENE, 75), new MaterialVolume(Materials.CARBON_T_P, 2)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_MOD, 1000)], [new MaterialVolume(Materials.BENZENE, 150), new MaterialVolume(Materials.CARBON_T_P, 2)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_MOD, 1000)], [new MaterialVolume(Materials.NAPHTA, 125), new MaterialVolume(Materials.CARBON_T_P, 2)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_MOD, 1000)], [new MaterialVolume(Materials.BUTADIENE, 75), new MaterialVolume(Materials.CARBON_T_P, 2)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_MOD, 1000)], [new MaterialVolume(Materials.PROPANE, 35), new MaterialVolume(Materials.CARBON_T_P, 2)], 30, Machine.Distillery),
    // cracked light fuel distillating - s sev
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.BUTENE, 65), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.NAPHTA, 100), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.PROPANE, 50), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.METHANE_GAS, 250), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.HEAVY_FUEL, 50), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.BUTADIENE, 50), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.ETHANE, 50), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.BENZENE, 150), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.ETHYLENE, 250), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.TOLUENE, 30), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.LIGHT_FUEL_S_SEV, 1000)], [new MaterialVolume(Materials.PROPENE, 250), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),

    // cracked naphta distillating - h mod
    new Recipe([new MaterialVolume(Materials.NAPHTA_H_MOD, 100)], [new MaterialVolume(Materials.ETHANE, 40)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_H_MOD, 100)], [new MaterialVolume(Materials.METHANE_GAS, 40)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_H_MOD, 100)], [new MaterialVolume(Materials.PROPANE, 110)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_H_MOD, 100)], [new MaterialVolume(Materials.BUTANE, 20)], 30, Machine.Distillery),
    // cracked light fuel distillating - h lig
    new Recipe([new MaterialVolume(Materials.NAPHTA_H_LIG, 100)], [new MaterialVolume(Materials.ETHANE, 25)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_H_LIG, 100)], [new MaterialVolume(Materials.BUTANE, 80)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_H_LIG, 100)], [new MaterialVolume(Materials.PROPANE, 30)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_H_LIG, 100)], [new MaterialVolume(Materials.METHANE_GAS, 25)], 30, Machine.Distillery),
    // cracked light fuel distillating - h sev
    new Recipe([new MaterialVolume(Materials.NAPHTA_H_SEV, 100)], [new MaterialVolume(Materials.ETHANE, 150)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_H_SEV, 100)], [new MaterialVolume(Materials.METHANE_GAS, 150)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_H_SEV, 200)], [new MaterialVolume(Materials.PROPANE, 25)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_H_SEV, 200)], [new MaterialVolume(Materials.BUTANE, 25)], 30, Machine.Distillery),
    // cracked naphta distillating - s lig
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_LIG, 1000)], [new MaterialVolume(Materials.BENZENE, 150), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_LIG, 1000)], [new MaterialVolume(Materials.TOLUENE, 40), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_LIG, 1000)], [new MaterialVolume(Materials.BUTADIENE, 150), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_LIG, 1000)], [new MaterialVolume(Materials.ETHANE, 35), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_LIG, 1000)], [new MaterialVolume(Materials.HEAVY_FUEL, 75), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_LIG, 1000)], [new MaterialVolume(Materials.PROPANE, 15), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_LIG, 1000)], [new MaterialVolume(Materials.LIGHT_FUEL, 150), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_LIG, 1000)], [new MaterialVolume(Materials.PROPENE, 200), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_LIG, 1000)], [new MaterialVolume(Materials.BUTENE, 80), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_LIG, 1000)], [new MaterialVolume(Materials.METHANE_GAS, 200), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_LIG, 1000)], [new MaterialVolume(Materials.ETHYLENE, 200), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    // cracked naphta distillating - s mod
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_MOD, 500)], [new MaterialVolume(Materials.PROPENE, 200), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_MOD, 500)], [new MaterialVolume(Materials.LIGHT_FUEL, 50), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_MOD, 500)], [new MaterialVolume(Materials.METHANE_GAS, 175), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_MOD, 500)], [new MaterialVolume(Materials.HEAVY_FUEL, 25), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_MOD, 500)], [new MaterialVolume(Materials.ETHANE, 25), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_MOD, 500)], [new MaterialVolume(Materials.TOLUENE, 15), new MaterialVolume(Materials.CARBON_T_P, 1)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_MOD, 1000)], [new MaterialVolume(Materials.PROPANE, 15), new MaterialVolume(Materials.CARBON_T_P, 2)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_MOD, 1000)], [new MaterialVolume(Materials.BUTADIENE, 50), new MaterialVolume(Materials.CARBON_T_P, 2)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_MOD, 1000)], [new MaterialVolume(Materials.ETHYLENE, 175), new MaterialVolume(Materials.CARBON_T_P, 2)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_MOD, 1000)], [new MaterialVolume(Materials.BENZENE, 125), new MaterialVolume(Materials.CARBON_T_P, 2)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_MOD, 1000)], [new MaterialVolume(Materials.BUTENE, 65), new MaterialVolume(Materials.CARBON_T_P, 2)], 30, Machine.Distillery),
    // cracked naphta distillating - s sev
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_SEV, 1000)], [new MaterialVolume(Materials.ETHYLENE, 500), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_SEV, 1000)], [new MaterialVolume(Materials.PROPANE, 15), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_SEV, 1000)], [new MaterialVolume(Materials.TOLUENE, 20), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_SEV, 1000)], [new MaterialVolume(Materials.BUTENE, 50), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_SEV, 1000)], [new MaterialVolume(Materials.BENZENE, 100), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_SEV, 1000)], [new MaterialVolume(Materials.LIGHT_FUEL, 50), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_SEV, 1000)], [new MaterialVolume(Materials.BUTADIENE, 50), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_SEV, 1000)], [new MaterialVolume(Materials.ETHANE, 65), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_SEV, 1000)], [new MaterialVolume(Materials.METHANE_GAS, 500), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_SEV, 1000)], [new MaterialVolume(Materials.PROPENE, 300), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.NAPHTA_S_SEV, 1000)], [new MaterialVolume(Materials.HEAVY_FUEL, 25), new MaterialVolume(Materials.CARBON_T_P, 3)], 30, Machine.Distillery),

    // Wood pyrolize

    new Recipe([new MaterialVolume(Materials.WOOD, 20), new MaterialVolume(Materials.STEAM, 1000)], [new MaterialVolume(Materials.COAL_GAS, 1440), new MaterialVolume(Materials.CHARCOAL, 24)], 30, Machine.PyrolizeOven),
    new Recipe([new MaterialVolume(Materials.WOOD, 16)], [new MaterialVolume(Materials.WOOD_VINEGAR, 3000), new MaterialVolume(Materials.CHARCOAL, 20)], 64, Machine.PyrolizeOven),
    new Recipe([new MaterialVolume(Materials.WOOD, 16)], [new MaterialVolume(Materials.WOOD_TAR, 1500), new MaterialVolume(Materials.CHARCOAL, 20)], 64, Machine.PyrolizeOven),
    new Recipe([new MaterialVolume(Materials.WOOD, 16)], [new MaterialVolume(Materials.CREOSOTE_OIL, 4000), new MaterialVolume(Materials.CHARCOAL, 20)], 64, Machine.PyrolizeOven),
    new Recipe([new MaterialVolume(Materials.WOOD, 16), new MaterialVolume(Materials.NITROGEN, 1000)], [new MaterialVolume(Materials.WOOD_TAR, 1500), new MaterialVolume(Materials.CHARCOAL, 20)], 96, Machine.PyrolizeOven),
    new Recipe([new MaterialVolume(Materials.WOOD, 16), new MaterialVolume(Materials.NITROGEN, 1000)], [new MaterialVolume(Materials.CHARCOAL_BYPRODUCTS, 4000), new MaterialVolume(Materials.CHARCOAL, 20)], 96, Machine.PyrolizeOven),
    new Recipe([new MaterialVolume(Materials.WOOD, 16), new MaterialVolume(Materials.NITROGEN, 1000)], [new MaterialVolume(Materials.WOOD_GAS, 1500), new MaterialVolume(Materials.CHARCOAL, 20)], 96, Machine.PyrolizeOven),
    new Recipe([new MaterialVolume(Materials.WOOD, 16), new MaterialVolume(Materials.NITROGEN, 1000)], [new MaterialVolume(Materials.WOOD_VINEGAR, 3000), new MaterialVolume(Materials.CHARCOAL, 20)], 96, Machine.PyrolizeOven),
    new Recipe([new MaterialVolume(Materials.WOOD, 16), new MaterialVolume(Materials.NITROGEN, 1000)], [new MaterialVolume(Materials.CREOSOTE_OIL, 4000), new MaterialVolume(Materials.CHARCOAL, 20)], 96, Machine.PyrolizeOven),
    new Recipe([new MaterialVolume(Materials.WOOD, 16)], [new MaterialVolume(Materials.HEAVY_OIL, 200), new MaterialVolume(Materials.ASHES, 4)], 192, Machine.PyrolizeOven),

    new Recipe([new MaterialVolume(Materials.WOOD_VINEGAR, 200)], [new MaterialVolume(Materials.ETHANOL, 2)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.WOOD_VINEGAR, 200)], [new MaterialVolume(Materials.METHYL_ACETATE, 2)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.WOOD_VINEGAR, 200)], [new MaterialVolume(Materials.ACETONE, 10)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.WOOD_VINEGAR, 200)], [new MaterialVolume(Materials.METHANOL, 60)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.WOOD_VINEGAR, 200)], [new MaterialVolume(Materials.ACETIC_ACID, 20)], 64, Machine.Distillery),
    // + water

    new Recipe([new MaterialVolume(Materials.WOOD_TAR, 200)], [new MaterialVolume(Materials.DIMETYLBENZENE, 40)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.WOOD_TAR, 200)], [new MaterialVolume(Materials.TOLUENE, 15)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.WOOD_TAR, 200)], [new MaterialVolume(Materials.PHENOL, 15)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.WOOD_TAR, 200)], [new MaterialVolume(Materials.CREOSOTE_OIL, 60)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.WOOD_TAR, 200)], [new MaterialVolume(Materials.BENZENE, 70)], 64, Machine.Distillery),

    new Recipe([new MaterialVolume(Materials.WOOD_GAS, 200)], [new MaterialVolume(Materials.METHANE_GAS, 26)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.WOOD_GAS, 200)], [new MaterialVolume(Materials.ETHYLENE, 4)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.WOOD_GAS, 200)], [new MaterialVolume(Materials.CO2_GAS, 98)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.WOOD_GAS, 200)], [new MaterialVolume(Materials.HYDROGEN, 4)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.WOOD_GAS, 200)], [new MaterialVolume(Materials.CARBON_MONOXIDE, 68)], 64, Machine.Distillery),

    new Recipe([new MaterialVolume(Materials.CREOSOTE_OIL, 25)], [new MaterialVolume(Materials.LUBRICANT, 8)], 30, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.CREOSOTE_OIL, 750)], [new MaterialVolume(Materials.LUBRICANT, 750), new MaterialVolume(Materials.TALC, 1)], 4, Machine.Brewery),

    new Recipe([new MaterialVolume(Materials.WOOD_TAR, 200)], [new MaterialVolume(Materials.DIMETYLBENZENE, 40)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.WOOD_TAR, 200)], [new MaterialVolume(Materials.TOLUENE, 15)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.WOOD_TAR, 200)], [new MaterialVolume(Materials.PHENOL, 15)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.WOOD_TAR, 200)], [new MaterialVolume(Materials.CREOSOTE_OIL, 60)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.WOOD_TAR, 200)], [new MaterialVolume(Materials.BENZENE, 70)], 64, Machine.Distillery),

    new Recipe([new MaterialVolume(Materials.CHARCOAL_BYPRODUCTS, 1000)], [new MaterialVolume(Materials.WOOD_TAR, 250)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.CHARCOAL_BYPRODUCTS, 1000)], [new MaterialVolume(Materials.DIMETYLBENZENE, 100)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.CHARCOAL_BYPRODUCTS, 1000)], [new MaterialVolume(Materials.WOOD_GAS, 250)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.CHARCOAL_BYPRODUCTS, 1000)], [new MaterialVolume(Materials.WOOD_VINEGAR, 400)], 64, Machine.Distillery),
    new Recipe([new MaterialVolume(Materials.CHARCOAL_BYPRODUCTS, 40)], [new MaterialVolume(Materials.DIMETYLBENZENE, 4)], 120, Machine.Distillery),

    new Recipe([new MaterialVolume(Materials.COAL, 12)], [new MaterialVolume(Materials.COAL_TAR, 2200)], 120, Machine.PyrolizeOven),
    new Recipe([new MaterialVolume(Materials.COAL_COKE, 8)], [new MaterialVolume(Materials.COAL_TAR, 3400), new MaterialVolume(Materials.ASHES, 1)], 240, Machine.PyrolizeOven),
    new Recipe([new MaterialVolume(Materials.COAL, 16), new MaterialVolume(Materials.STEAM, 1000)], [new MaterialVolume(Materials.COAL_COKE, 10), new MaterialVolume(Materials.COAL_GAS, 2880)], 120, Machine.PyrolizeOven),
    new Recipe([new MaterialVolume(Materials.COAL, 16)], [new MaterialVolume(Materials.COAL_COKE, 16), new MaterialVolume(Materials.CREOSOTE_OIL, 8000)], 64, Machine.PyrolizeOven),

];